### ISSUE TITLE
New data raw repo

### ISSUE THREAD

**Issue by christophsax** [trendecon/data#1]
@angelicambg 

The latest version of gtrendecon writes to this repo, not to itself anymore, which is a first step towards repo clean up. You need to clone the repo and keep it in the same directory as gtrendecon.

I also move the scripts in gtrendecon to the `inst` folder and adjusted the REAMDE:

https://github.com/christophsax/gtrendecon/tree/master/inst/script

You can try to do another update to `trendecon/data-raw` and `trendecon/data`. Pushing to `christophsax/gtrenecon` is not needed anymore.

Let me know if it doesn't work.

**Comment by christophsax** [comment]
I updated the path structure a little. In theory, `proc_all()` should work as before. You can continue to use it as before. If something breaks, let me know.

Going forward, `proc_all()` should be replaced by `proc_trendecon_ch()` which does more or less the same but only writes to the current working directory.

As described here:

https://github.com/trendecon/data-raw

This should simplify automated updating, on which Patrick is working now.

**Comment by angelicambg** [comment]
I just run `proc_all("..")` but got this error:
`failed to create the optimizer; optimization not done
Error in if (m$stan.fit$return_code != 0) { : argument is of length zero`

**Comment by christophsax** [comment]
I look into it tomorrow. Error sounds pretty crazy, perhaps from prophet?

**Comment by angelicambg** [comment]
Yes, probably. Since prophet uses stan, and I found this https://github.com/stan-dev/rstan/issues/353.
because I run `proc_trendecon_ch()` and got something similar
`Error in cpp_object_initializer(.self, .refClassDef, ...) : 
  could not find function "cpp_object_initializer"
failed to create the optimizer; optimization not done
Error in if (m$stan.fit$return_code != 0) { : argument is of length zero`

**Comment by christophsax** [comment]
I cannot reproduce, it works on my laptop.

```r
> packageVersion("prophet")
[1] ‘0.6.1’
```

I see that @pat-s is working on setting up the automatization, so let's see if he succeeds.

**Comment by angelicambg** [comment]
I have the same version of prophet, but I updated all the others packages and `proc_all("..")` it's running now.

**Comment by christophsax** [comment]
Nice. Patrick has now set up the automatic run and we will see how it works.

**Comment by angelicambg** [comment]
I saw that the indicators are on [data-raw/indicator](https://github.com/trendecon/data-raw/tree/master/indicator)  folder. Should I use this for the webpage, or I should wait when the files are inside [data-raw/daily](https://github.com/trendecon/data-raw/tree/master/daily) folder

**Comment by christophsax** [comment]
Renamed to `data`. The website should self update now.
