### ISSUE TITLE
Is 'daily' directory still used in production?

### ISSUE THREAD

**Issue by karoliskoncevicius** [trendecon/data#10]
I am wondering if the daily/ directory is still used by the scripts? Is it safe to delete?

If not it might be a good idea to remove it. And then I can delete the line from proc_trendecon_ch() which still writes the output to two different locations.

**Comment by christophsax** [comment]
The website uses it. Need to be changed there first.

**Comment by pat-s** [comment]
AFAIR we also deply to `daily` via GHA?

**Comment by christophsax** [comment]
We do now, but we want to use data/ch only. Currently we deploy to both. We need to change dashboard, then delete daily.

**Comment by karoliskoncevicius** [comment]
@christophsax pull request for that is currently awaiting review in dashboard.

**Comment by karoliskoncevicius** [comment]
Deleted daily as it should no longer be used in production.

Will restore if something breaks.
