### ISSUE TITLE
Breaking the API

### ISSUE THREAD

**Issue by mbannert** [trendecon/data#15]
I realized y'all broke the API by introducing country folders and deprecating the daily folder. Hence I thought I share a few ideas to avoid such breaks in the future when the project is growing further. Also, thanks to Airflow we were covered quite well and were able to react quickly, but others might only realize upon needing the data adhoc that something is wrong. 

However, I suggest to 

- add a deprecation warning to the README of the data repository, front and center and maybe even to the website. Some 'new API splash icon'. 

- consider keeping an old API / thinking about a redirect, like google does it with /api/v1 , /api/v2 etc. 

I think we can close this issue, just thought it might be helpful to raise this and stay in touch in case you react immediately an make another change 🌻

**Comment by christophsax** [comment]
Yes, yes, you are right. My bad!

**Comment by christophsax** [comment]
No further changes planned. Current solution is for the eternity.
