### ISSUE TITLE
"Merge conflict" error when re-running Actions manually.

### ISSUE THREAD

**Issue by karoliskoncevicius** [trendecon/data#17]
Today fixed one mistake in trendcon/trendcon which affected a location of a data file. After fixing it I wanted to re-run the GA actions manually, so that the website is updated to the correct version.

However when doing so I ran into issues (both on `dashboard` and on `data` repositories).

@pat-s maybe you can help me figure out what the problem here is. Here is a screenshot with the errors:

![Screenshot 2020-08-18 at 3 39 41 PM](https://user-images.githubusercontent.com/7273684/90514080-56a9b680-e169-11ea-99e0-e9158c4e8c3c.png)

**Comment by pat-s** [comment]
You triggered the run too early and faced a git race condition during deployment. Run it again and do not make any intermediate commits, then it should work.

**Comment by karoliskoncevicius** [comment]
Thanks! Will pin this issue for reference.
