### ISSUE TITLE
Look into Austria

### ISSUE THREAD

**Issue by christophsax** [trendecon/data#18]
Why does it look inverted? How do the underlying series look like? I would assume the raw  data is similar to DE and CH. 

So perhaps we should just omit the sign inversion?

In any case, we want an indicator that looks similar to CH and DE.

**Comment by karoliskoncevicius** [comment]
I think this is Principal Component issue, not a data issue.

Here are the results after proposed fix in trendecon:

    data <- read.csv("https://raw.githubusercontent.com/trendecon/data/dev_pc_sign_check/data/at/trendecon_sa.csv")
    tsbox::ts_plot(data, title = "Austria")

<img width="1003" alt="Screenshot 2020-09-02 at 11 32 26 PM" src="https://user-images.githubusercontent.com/7273684/92033592-94672b80-ed74-11ea-90c7-240a89d0228e.png">
