### ISSUE TITLE
Update frequency daily indicators

### ISSUE THREAD

**Issue by vzei** [trendecon/data#20]
Dear @karoliskoncevicius 
If I understood correctly, you are maintaining that data is fed to the website on an ongoing basis. I will use some a zoom-in of recent developments in some indicators as figures in a presentation next Wednesday 28 October. 

I noticed that today, the most recent data (e.g. for the perceived economic situation) was available for 17 October. I therefore wanted to ask how often the data is updated.
Any recent major issues that I should be aware of when presenting the data?

Thanks for your support!
Vera

**Comment by karoliskoncevicius** [comment]
Hello @vzei , you are correct - as of now I am maintaining the scripts for obtaining and preparing the data.

The files are updated once per day, last update was 16 hours ago, so another one will most likely run in 8 hours. There seems to be a known issue about last 3 days not being included. @christophsax mentioned in here: https://github.com/trendecon/gtrendecon/issues/19 . He says that it is possible to do something about it, but I haven't had the time to look into it properly yet.

For now, the situation like this: the data is updated once a day, but updates lag behind the current day by 3 days. So the data for last 3 days will be missing.

Other than that, there should be no issues. I found one around a month ago, but it should be fixed now in all of the files. More details can be found here: https://github.com/trendecon/data/issues/12

**Comment by vzei** [comment]
Thanks @karoliskoncevicius for this detailed answer. @christophsax do you have any chance to look into the 3 days lag any time soon? trendEcon sees renewed interest and the KOF Mobilitätsindikator is also problematic because the city of Zurich only updates the daily series once per week (dumb indeed...).

**Comment by christophsax** [comment]
It's am major extension and I asked @karoliskoncevicius to work on it: https://github.com/trendecon/gtrendecon/issues/19.

closing this one.
