### ISSUE TITLE
github action failed

### ISSUE THREAD

**Issue by angelicambg** [trendecon/data#5]
Hi @pat-s could you take a look at this error? at the stage deploy `tic` tried to push to the repo but It failed due to permissions.

**Comment by pat-s** [comment]
Thanks, fixed it.

**Comment by angelicambg** [comment]
Thanks! 

I think the same error is happening in the [dashboard ](https://github.com/trendecon/dashboard/actions) repo

**Comment by pat-s** [comment]
Thanks. Fixed.
